"""PlatformIO pre-build hook: derive the firmware version string.

Versioning rule (SemVer MAJOR.MINOR.PATCH):
  - every distinct git branch gets its own MINOR, allocated monotonically the
    first time the branch is built  -> "new branch = new minor"
  - every build bumps that branch's PATCH                  -> "new build = new patch"
  - MAJOR is manual (edit "major" in the state file for a release).

State lives in firmware/.fw_version.json (gitignored, local to the build
machine). The result is written to firmware/src/version_gen.h rather than
injected as a -D macro on purpose: a changing global CPPDEFINE busts SCons'
build cache and forces a full recompile every build, whereas a generated header
only recompiles the handful of translation units that include version.h.

Wire it in platformio.ini per env:  extra_scripts = pre:tools/gen_version.py
"""
import json
import subprocess
from pathlib import Path

Import("env")  # noqa: F821 — injected by PlatformIO/SCons

PROJECT_DIR = Path(env["PROJECT_DIR"])          # the firmware/ dir
STATE_FILE = PROJECT_DIR / ".fw_version.json"
OUT_HEADER = PROJECT_DIR / "src" / "version_gen.h"


def _git(*args, default=""):
    try:
        return subprocess.check_output(
            ["git", *args], cwd=str(PROJECT_DIR), stderr=subprocess.DEVNULL
        ).decode().strip()
    except Exception:
        return default


def _load_state():
    if STATE_FILE.exists():
        try:
            return json.loads(STATE_FILE.read_text())
        except (ValueError, OSError):
            pass
    return {"major": 0, "next_minor": 1, "branches": {}}


branch = _git("rev-parse", "--abbrev-ref", "HEAD", default="nogit")

state = _load_state()
state.setdefault("major", 0)
state.setdefault("next_minor", 1)
state.setdefault("branches", {})

entry = state["branches"].get(branch)
if entry is None:
    # First build on this branch -> claim the next free minor, patch starts at 0.
    entry = {"minor": state["next_minor"], "patch": 0}
    state["next_minor"] += 1
    state["branches"][branch] = entry
else:
    # Subsequent build on a known branch -> bump patch.
    entry["patch"] += 1

version = f'{state["major"]}.{entry["minor"]}.{entry["patch"]}'

sha = _git("rev-parse", "--short", "HEAD", default="nogit")
dirty = "+dirty" if _git("status", "--porcelain") else ""
git_desc = f"{sha}{dirty}"

STATE_FILE.write_text(json.dumps(state, indent=2) + "\n")

OUT_HEADER.write_text(
    "// Generated by tools/gen_version.py — do not edit, do not commit.\n"
    "#pragma once\n"
    f'#define FW_VERSION "{version}"\n'
    f'#define FW_GIT "{git_desc}"\n'
)

print(f"gen_version: branch={branch} FW_VERSION={version} git={git_desc}")
